# font config

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

# Fallback font (just incase)
font_family fallback IBM Plex Mono

font_size 12.0
line_height 1.15


# window config

window_padding_width 12

# Transparency
background_opacity 0.90

# Blur 
background_blur 32

# Cleannnnn
hide_window_decorations yes


# CURSOR

cursor_shape block
cursor_blink_interval 0.5


# SCROLLBACK

scrollback_lines 3000


# behaviour

copy_on_select no
strip_trailing_spaces smart
enable_audio_bell no


# KEYBINDS

map ctrl+shift+n new_window
map ctrl+t new_tab

map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0



# tabs

tab_bar_style powerline
tab_bar_align left

# Optional: cleaner inactive tabs
inactive_tab_opacity 0.7



# Dank shell

shell_integration enabled


# rendering stuff

disable_ligatures never

# GPU rendering tweaks
repaint_delay 10
input_delay 3

# themes

#  custom configs
include dank-tabs.conf
include dank-theme.conf